---
apiVersion: v1
kind: Pod
metadata:
  name: mdr-ra-opal-server
spec:
  hostname: opal
  restartPolicy: Always
  containers:
    - name: opal
      image: "docker.io/obiba/opal:5.1.2" # ANSIBLE REPLACE MARKER OBIBA IMAGE
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort:
          protocol: TCP
      volumeMounts:
        - name: opal-data
          mountPath: /srv
      envFrom:
        - configMapRef:
            name: opal-env
        - configMapRef:
            name: rock-env
        - configMapRef:
            name: postgres-env
      env:
        - name: OPAL_ADMINISTRATOR_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: opal-env
              key: OPAL_ADMINISTRATOR_PASSWORD
        - name: POSTGRESDATA_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-env
              key: POSTGRESDATA_DATABASE
        - name: POSTGRESDATA_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-env
              key: POSTGRESDATA_HOST
        - name: POSTGRESDATA_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-env
              key: POSTGRESDATA_USER
        - name: POSTGRESDATA_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-env
              key: POSTGRESDATA_PASSWORD
        - name: ROCK_HOSTS
          valueFrom:
            configMapKeyRef:
              name: rock-env
              key: ROCK_HOSTS
  volumes:
    - name: opal-data
      hostPath:
        path: /opt/mdr-ra/db/opal
        type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: mdr-ra-postgres
spec:
  hostname: postgres
  restartPolicy: OnFailure
  containers:
    - name: postgres
      image: "docker.io/bitnami/postgresql:17.4.0" # ANSIBLE REPLACE MARKER POSTGRES IMAGE
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: postgres-data
          mountPath: /bitnami/postgresql
      envFrom:
        - configMapRef:
            name: postgres-env
      env:
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-env
              key: POSTGRES_DB
        - name: POSTGRESQL_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-env
              key: POSTGRES_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-env
              key: POSTGRES_PASSWORD
  volumes:
    - name: postgres-data
      hostPath:
        path: /opt/mdr-ra/db/postgres
        type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: mdr-ra-rock
spec:
  hostname: rock
  restartPolicy: Always
  containers:
    - name: rock
      image: "docker.io/infomics/rock-omics2:latest" # ANSIBLE REPLACE MARKER ROCK IMAGE
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8085
          protocol: TCP
      envFrom:
        - configMapRef:
            name: rock-env
      volumeMounts:
        - mountPath: /var/lib/rock/R/library
          name: mdr-ra-rock-dependencies
  volumes:
    - name: mdr-ra-rock-dependencies
      persistentVolumeClaim:
        claimName: mdr-ra-rock-dependencies
---
apiVersion: v1
kind: Pod
metadata:
  name: mdr-ra-http-server
spec:
  hostname: nginx
  restartPolicy: Always
  containers:
    - name: nginx
      image: "quay.io/pluribus_one/nginx-modsec:1.27.0-3" # ANSIBLE REPLACE MARKER NGINX IMAGE
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4443
          hostPort: 8000 # ANSIBLE REPLACE MARKER HTTPS PORT
          protocol: TCP
      volumeMounts:
        - name: nginx-config
          mountPath: /opt/bitnami/nginx/conf/server_blocks/server.conf
        - name: https-certs
          mountPath: /bitnami/certs
  volumes:
    - name: nginx-config
      hostPath:
        path: /opt/mdr-ra/nginx/server.conf
        type: File
    - name: https-certs
      hostPath:
        path: /opt/mdr-ra/https/cert
        type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opal-env
data:
  OPAL_PORT: 8080
  OPAL_ADMINISTRATOR_PASSWORD: administrator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
data:
  POSTGRESDATA_DATABASE: opal
  POSTGRESDATA_HOST: mdr-ra-postgres
  POSTGRESDATA_USER: opal
  POSTGRESDATA_PASSWORD: password
  POSTGRES_DB: opal
  POSTGRES_USER: opal
  POSTGRES_PASSWORD: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rock-env
data:
  ROCK_HOSTS: "mdr-ra-rock:8085"
